
# Loads default set of integrations. Do not remove.
default_config:

http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.10.5    # Nginx Proxy Manager IP
    - 127.0.0.1
  cors_allowed_origins:
    - "https://606.landcameras.com"
  ip_ban_enabled: true
  login_attempts_threshold: 5


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
homeassistant:
  packages: !include_dir_named packages

template:

command_line:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
bluetooth:

logger:
  default: info
